win and linux tests

diff --git a/.github/workflows/all_apps_cicd.yml b/.github/workflows/all_apps_cicd.yml
--- a/.github/workflows/all_apps_cicd.yml
+++ b/.github/workflows/all_apps_cicd.yml
@@ -37,5 +37,41 @@ jobs:
         name: Unit Tests Windows  # Name of the check run which will be created
         path: ./*.Tests.trx  # Path to test results
         reporter: dotnet-trx  # Format of test results
+
+  build_and_unittest_linux:
+    runs-on: "ubuntu-latest"
+    permissions:
+      id-token: write
+      contents: read
+      checks: write
+      
+    steps:
+    - uses: actions/checkout@v3
+    - uses: actions/setup-dotnet@v3
+      with:
+        dotnet-version: '6.0.x'
+    
+    - name: Install dependencies
+      run: dotnet restore
+
+    - name: Build all projects
+      run: dotnet build --no-restore
+
+    - name: Run unit tests
+      uses: Amadevus/pwsh-script@v2.0.3
+      id: dotnet_test
+      with:
+        script: |
+                 dir "*.Tests.csproj" -Recurse | %{dotnet test  $PSItem.FullName --logger ("trx;LogFileName=" + ($PSItem.Name -replace ".csproj", ".trx")) --no-restore --no-build}
+                 dir "*.Tests.trx" -Recurse | %{ copy-item -Path $PSItem.FullName };
+    - run: echo '${{ steps.dotnet_test.outputs.result }}'
+
+    - name: Create test report
+      uses: dorny/test-reporter@v1.6.0
+      if: success() || failure()  # run this step even if previous step failed
+      with:
+        name: Unit Tests Windows  # Name of the check run which will be created
+        path: ./*.Tests.trx  # Path to test results
+        reporter: dotnet-trx  # Format of test results
     
     
