Unit tests with results report

diff --git a/.github/workflows/all_apps_cicd.yml b/.github/workflows/all_apps_cicd.yml
--- a/.github/workflows/all_apps_cicd.yml
+++ b/.github/workflows/all_apps_cicd.yml
@@ -10,9 +10,30 @@ jobs:
     - uses: actions/setup-dotnet@v3
       with:
         dotnet-version: '6.0.x'
+    
     - name: Install dependencies
       run: dotnet restore
-    - name: Build
-      run: dotnet build
-    - name: Test with the dotnet CLI
-      run: dotnet test
+    
+    - name: Build all projects
+      uses: Amadevus/pwsh-script@v2.0.3
+      id: dotnet_build
+      with:
+        script: dir "*.csproj" -Recurse | %{dotnet build  $PSItem.FullName --no-restore}
+    - run: echo '${{ steps.dotnet_build.outputs.result }}'
+
+    - name: Run unit tests
+      uses: Amadevus/pwsh-script@v2.0.3
+      id: dotnet_test
+      with:
+        script: |
+                 dir "*.Tests.csproj" -Recurse | %{dotnet test  $PSItem.FullName --logger ("trx;LogFileName=" + ($PSItem.Name -replace ".csproj", ".trx")) /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --no-restore --no-build}
+                 dir "*.Tests.trx" -Recurse | %{ copy-item -Path $PSItem.FullName };
+    - run: echo '${{ steps.dotnet_test.outputs.result }}'
+
+    - name: Test Report
+      uses: dorny/test-reporter@v1.6.0
+      if: success() || failure()  # run this step even if previous step failed
+      with:
+        name: Unit Tests Linux  # Name of the check run which will be created
+        path: ./*.Tests.trx  # Path to test results
+        reporter: dotnet-trx  # Format of test results
